// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _kmeans_top_HH_
#define _kmeans_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "classify_image.h"

namespace ap_rtl {

struct kmeans_top : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > image_r_address0;
    sc_out< sc_logic > image_r_ce0;
    sc_in< sc_lv<8> > image_r_q0;
    sc_out< sc_lv<10> > image_r_address1;
    sc_out< sc_logic > image_r_ce1;
    sc_in< sc_lv<8> > image_r_q1;
    sc_out< sc_lv<1> > result_address0;
    sc_out< sc_logic > result_ce0;
    sc_out< sc_logic > result_we0;
    sc_out< sc_lv<32> > result_d0;
    sc_out< sc_lv<1> > result_address1;
    sc_out< sc_logic > result_ce1;
    sc_out< sc_logic > result_we1;
    sc_out< sc_lv<32> > result_d1;


    // Module declarations
    kmeans_top(sc_module_name name);
    SC_HAS_PROCESS(kmeans_top);

    ~kmeans_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    classify_image* grp_classify_image_fu_45;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > grp_classify_image_fu_45_ap_start;
    sc_signal< sc_logic > grp_classify_image_fu_45_ap_done;
    sc_signal< sc_logic > grp_classify_image_fu_45_ap_idle;
    sc_signal< sc_logic > grp_classify_image_fu_45_ap_ready;
    sc_signal< sc_lv<10> > grp_classify_image_fu_45_image_r_address0;
    sc_signal< sc_logic > grp_classify_image_fu_45_image_r_ce0;
    sc_signal< sc_lv<10> > grp_classify_image_fu_45_image_r_address1;
    sc_signal< sc_logic > grp_classify_image_fu_45_image_r_ce1;
    sc_signal< sc_lv<32> > grp_classify_image_fu_45_ap_return_0;
    sc_signal< sc_lv<32> > grp_classify_image_fu_45_ap_return_1;
    sc_signal< sc_logic > grp_classify_image_fu_45_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_classify_image_fu_45_ap_start();
    void thread_image_r_address0();
    void thread_image_r_address1();
    void thread_image_r_ce0();
    void thread_image_r_ce1();
    void thread_result_address0();
    void thread_result_address1();
    void thread_result_ce0();
    void thread_result_ce1();
    void thread_result_d0();
    void thread_result_d1();
    void thread_result_we0();
    void thread_result_we1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
