// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "classify_image.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic classify_image::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic classify_image::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<43> classify_image::ap_ST_fsm_state1 = "1";
const sc_lv<43> classify_image::ap_ST_fsm_state2 = "10";
const sc_lv<43> classify_image::ap_ST_fsm_state3 = "100";
const sc_lv<43> classify_image::ap_ST_fsm_state4 = "1000";
const sc_lv<43> classify_image::ap_ST_fsm_state5 = "10000";
const sc_lv<43> classify_image::ap_ST_fsm_state6 = "100000";
const sc_lv<43> classify_image::ap_ST_fsm_state7 = "1000000";
const sc_lv<43> classify_image::ap_ST_fsm_state8 = "10000000";
const sc_lv<43> classify_image::ap_ST_fsm_state9 = "100000000";
const sc_lv<43> classify_image::ap_ST_fsm_state10 = "1000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state11 = "10000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state12 = "100000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<43> classify_image::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<32> classify_image::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> classify_image::ap_const_lv32_1 = "1";
const sc_lv<1> classify_image::ap_const_lv1_1 = "1";
const sc_lv<32> classify_image::ap_const_lv32_2 = "10";
const sc_lv<1> classify_image::ap_const_lv1_0 = "0";
const sc_lv<32> classify_image::ap_const_lv32_3 = "11";
const sc_lv<32> classify_image::ap_const_lv32_4 = "100";
const sc_lv<32> classify_image::ap_const_lv32_9 = "1001";
const sc_lv<32> classify_image::ap_const_lv32_28 = "101000";
const sc_lv<32> classify_image::ap_const_lv32_29 = "101001";
const sc_lv<4> classify_image::ap_const_lv4_0 = "0000";
const sc_lv<32> classify_image::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<13> classify_image::ap_const_lv13_0 = "0000000000000";
const sc_lv<27> classify_image::ap_const_lv27_0 = "000000000000000000000000000";
const sc_lv<10> classify_image::ap_const_lv10_0 = "0000000000";
const sc_lv<64> classify_image::ap_const_lv64_412E848000000000 = "100000100101110100001001000000000000000000000000000000000000000";
const sc_lv<32> classify_image::ap_const_lv32_A = "1010";
const sc_lv<13> classify_image::ap_const_lv13_310 = "1100010000";
const sc_lv<4> classify_image::ap_const_lv4_A = "1010";
const sc_lv<4> classify_image::ap_const_lv4_1 = "1";
const sc_lv<10> classify_image::ap_const_lv10_310 = "1100010000";
const sc_lv<10> classify_image::ap_const_lv10_1 = "1";
const sc_lv<32> classify_image::ap_const_lv32_3F = "111111";
const sc_lv<32> classify_image::ap_const_lv32_34 = "110100";
const sc_lv<32> classify_image::ap_const_lv32_3E = "111110";
const sc_lv<12> classify_image::ap_const_lv12_C01 = "110000000001";
const sc_lv<32> classify_image::ap_const_lv32_B = "1011";
const sc_lv<11> classify_image::ap_const_lv11_3FF = "1111111111";
const sc_lv<32> classify_image::ap_const_lv32_35 = "110101";
const sc_lv<32> classify_image::ap_const_lv32_54 = "1010100";
const sc_lv<32> classify_image::ap_const_lv32_2A = "101010";
const bool classify_image::ap_const_boolean_1 = true;

classify_image::classify_image(sc_module_name name) : sc_module(name), mVcdFile(0) {
    centroids_0_U = new classify_image_centroids_0("centroids_0_U");
    centroids_0_U->clk(ap_clk);
    centroids_0_U->reset(ap_rst);
    centroids_0_U->address0(centroids_0_address0);
    centroids_0_U->ce0(centroids_0_ce0);
    centroids_0_U->q0(centroids_0_q0);
    kmeans_top_ddiv_64ns_64ns_64_31_1_U1 = new kmeans_top_ddiv_64ns_64ns_64_31_1<1,31,64,64,64>("kmeans_top_ddiv_64ns_64ns_64_31_1_U1");
    kmeans_top_ddiv_64ns_64ns_64_31_1_U1->clk(ap_clk);
    kmeans_top_ddiv_64ns_64ns_64_31_1_U1->reset(ap_rst);
    kmeans_top_ddiv_64ns_64ns_64_31_1_U1->din0(ap_var_for_const0);
    kmeans_top_ddiv_64ns_64ns_64_31_1_U1->din1(tmp_s_reg_500);
    kmeans_top_ddiv_64ns_64ns_64_31_1_U1->ce(ap_var_for_const1);
    kmeans_top_ddiv_64ns_64ns_64_31_1_U1->dout(grp_fu_168_p2);
    kmeans_top_uitodp_32ns_64_6_1_U2 = new kmeans_top_uitodp_32ns_64_6_1<1,6,32,64>("kmeans_top_uitodp_32ns_64_6_1_U2");
    kmeans_top_uitodp_32ns_64_6_1_U2->clk(ap_clk);
    kmeans_top_uitodp_32ns_64_6_1_U2->reset(ap_rst);
    kmeans_top_uitodp_32ns_64_6_1_U2->din0(grp_fu_173_p0);
    kmeans_top_uitodp_32ns_64_6_1_U2->ce(ap_var_for_const1);
    kmeans_top_uitodp_32ns_64_6_1_U2->dout(grp_fu_173_p1);
    kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3 = new kmeans_top_mac_muladd_9s_9s_27s_27_1_1<1,1,9,9,27,27>("kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3");
    kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3->din0(grp_fu_431_p0);
    kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3->din1(grp_fu_431_p1);
    kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3->din2(class_min_dist_reg_145);
    kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3->dout(grp_fu_431_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( best_class_reg_109 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( p_Val2_6_fu_413_p3 );

    SC_METHOD(thread_best_class_1_cast3_fu_182_p1);
    sensitive << ( best_class_1_reg_98 );

    SC_METHOD(thread_c_0_best_class_fu_247_p3);
    sensitive << ( best_class_1_cast3_reg_444 );
    sensitive << ( best_class_reg_109 );
    sensitive << ( tmp_3_fu_241_p2 );

    SC_METHOD(thread_c_fu_192_p2);
    sensitive << ( best_class_1_reg_98 );

    SC_METHOD(thread_centroids_0_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_10_cast_fu_232_p1 );

    SC_METHOD(thread_centroids_0_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_class_min_dist_0_glo_fu_254_p3);
    sensitive << ( global_min_dist_reg_121 );
    sensitive << ( class_min_dist_cast_fu_237_p1 );
    sensitive << ( tmp_3_fu_241_p2 );

    SC_METHOD(thread_class_min_dist_cast_fu_237_p1);
    sensitive << ( class_min_dist_reg_145 );

    SC_METHOD(thread_diff_cast_fu_276_p1);
    sensitive << ( diff_reg_490 );

    SC_METHOD(thread_diff_fu_270_p2);
    sensitive << ( tmp_4_cast_fu_262_p1 );
    sensitive << ( tmp_5_cast_fu_266_p1 );

    SC_METHOD(thread_exitcond2_fu_186_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( best_class_1_reg_98 );

    SC_METHOD(thread_exitcond_fu_205_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( p_reg_157 );

    SC_METHOD(thread_grp_fu_173_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( global_min_dist_reg_121 );

    SC_METHOD(thread_grp_fu_431_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( diff_cast_fu_276_p1 );

    SC_METHOD(thread_grp_fu_431_p1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( diff_cast_fu_276_p1 );

    SC_METHOD(thread_image_r_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_1_fu_217_p1 );

    SC_METHOD(thread_image_r_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_isNeg_fu_328_p3);
    sensitive << ( sh_assign_fu_322_p2 );

    SC_METHOD(thread_mantissa_V_1_cast_fu_314_p1);
    sensitive << ( mantissa_V_fu_304_p4 );

    SC_METHOD(thread_mantissa_V_fu_304_p4);
    sensitive << ( tmp_V_1_fu_300_p1 );

    SC_METHOD(thread_next_mul_fu_176_p2);
    sensitive << ( phi_mul_reg_133 );

    SC_METHOD(thread_p_1_fu_211_p2);
    sensitive << ( p_reg_157 );

    SC_METHOD(thread_p_Val2_5_fu_400_p3);
    sensitive << ( isNeg_fu_328_p3 );
    sensitive << ( tmp_5_fu_386_p1 );
    sensitive << ( tmp_7_fu_390_p4 );

    SC_METHOD(thread_p_Val2_6_fu_413_p3);
    sensitive << ( p_Result_s_reg_510 );
    sensitive << ( p_Val2_5_reg_515 );
    sensitive << ( result_V_1_fu_408_p2 );

    SC_METHOD(thread_p_Val2_s_fu_279_p1);
    sensitive << ( x_assign_reg_505 );

    SC_METHOD(thread_r_V_1_fu_372_p2);
    sensitive << ( mantissa_V_1_cast_fu_314_p1 );
    sensitive << ( tmp_1_i_i_i_fu_358_p1 );

    SC_METHOD(thread_r_V_fu_366_p2);
    sensitive << ( mantissa_V_fu_304_p4 );
    sensitive << ( tmp_1_i_i_i_cast_fu_362_p1 );

    SC_METHOD(thread_result_V_1_fu_408_p2);
    sensitive << ( p_Val2_5_reg_515 );

    SC_METHOD(thread_sh_assign_2_cast_fu_354_p1);
    sensitive << ( ush_fu_346_p3 );

    SC_METHOD(thread_sh_assign_fu_322_p2);
    sensitive << ( tmp_i_i_i_i_cast1_fu_318_p1 );

    SC_METHOD(thread_tmp_10_cast_fu_232_p1);
    sensitive << ( tmp_2_fu_226_p2 );

    SC_METHOD(thread_tmp_1_cast_fu_222_p1);
    sensitive << ( p_reg_157 );

    SC_METHOD(thread_tmp_1_fu_217_p1);
    sensitive << ( p_reg_157 );

    SC_METHOD(thread_tmp_1_i_i_i_cast_fu_362_p1);
    sensitive << ( sh_assign_2_cast_fu_354_p1 );

    SC_METHOD(thread_tmp_1_i_i_i_fu_358_p1);
    sensitive << ( sh_assign_2_cast_fu_354_p1 );

    SC_METHOD(thread_tmp_2_fu_226_p2);
    sensitive << ( phi_mul_reg_133 );
    sensitive << ( tmp_1_cast_fu_222_p1 );

    SC_METHOD(thread_tmp_3_fu_241_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_205_p2 );
    sensitive << ( global_min_dist_reg_121 );
    sensitive << ( class_min_dist_cast_fu_237_p1 );

    SC_METHOD(thread_tmp_4_cast_fu_262_p1);
    sensitive << ( image_r_q0 );

    SC_METHOD(thread_tmp_5_cast_fu_266_p1);
    sensitive << ( centroids_0_q0 );

    SC_METHOD(thread_tmp_5_fu_386_p1);
    sensitive << ( tmp_9_fu_378_p3 );

    SC_METHOD(thread_tmp_7_fu_390_p4);
    sensitive << ( r_V_1_fu_372_p2 );

    SC_METHOD(thread_tmp_9_fu_378_p3);
    sensitive << ( r_V_fu_366_p2 );

    SC_METHOD(thread_tmp_V_1_fu_300_p1);
    sensitive << ( p_Val2_s_fu_279_p1 );

    SC_METHOD(thread_tmp_V_fu_290_p4);
    sensitive << ( p_Val2_s_fu_279_p1 );

    SC_METHOD(thread_tmp_i_i_i_cast_fu_342_p1);
    sensitive << ( tmp_i_i_i_fu_336_p2 );

    SC_METHOD(thread_tmp_i_i_i_fu_336_p2);
    sensitive << ( tmp_V_fu_290_p4 );

    SC_METHOD(thread_tmp_i_i_i_i_cast1_fu_318_p1);
    sensitive << ( tmp_V_fu_290_p4 );

    SC_METHOD(thread_ush_fu_346_p3);
    sensitive << ( sh_assign_fu_322_p2 );
    sensitive << ( isNeg_fu_328_p3 );
    sensitive << ( tmp_i_i_i_cast_fu_342_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_186_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_205_p2 );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "classify_image_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, image_r_address0, "(port)image_r_address0");
    sc_trace(mVcdFile, image_r_ce0, "(port)image_r_ce0");
    sc_trace(mVcdFile, image_r_q0, "(port)image_r_q0");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, centroids_0_address0, "centroids_0_address0");
    sc_trace(mVcdFile, centroids_0_ce0, "centroids_0_ce0");
    sc_trace(mVcdFile, centroids_0_q0, "centroids_0_q0");
    sc_trace(mVcdFile, next_mul_fu_176_p2, "next_mul_fu_176_p2");
    sc_trace(mVcdFile, next_mul_reg_439, "next_mul_reg_439");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, best_class_1_cast3_fu_182_p1, "best_class_1_cast3_fu_182_p1");
    sc_trace(mVcdFile, best_class_1_cast3_reg_444, "best_class_1_cast3_reg_444");
    sc_trace(mVcdFile, c_fu_192_p2, "c_fu_192_p2");
    sc_trace(mVcdFile, c_reg_452, "c_reg_452");
    sc_trace(mVcdFile, exitcond2_fu_186_p2, "exitcond2_fu_186_p2");
    sc_trace(mVcdFile, p_1_fu_211_p2, "p_1_fu_211_p2");
    sc_trace(mVcdFile, p_1_reg_465, "p_1_reg_465");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond_fu_205_p2, "exitcond_fu_205_p2");
    sc_trace(mVcdFile, c_0_best_class_fu_247_p3, "c_0_best_class_fu_247_p3");
    sc_trace(mVcdFile, class_min_dist_0_glo_fu_254_p3, "class_min_dist_0_glo_fu_254_p3");
    sc_trace(mVcdFile, diff_fu_270_p2, "diff_fu_270_p2");
    sc_trace(mVcdFile, diff_reg_490, "diff_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_fu_431_p3, "grp_fu_431_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_fu_173_p1, "grp_fu_173_p1");
    sc_trace(mVcdFile, tmp_s_reg_500, "tmp_s_reg_500");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_168_p2, "grp_fu_168_p2");
    sc_trace(mVcdFile, x_assign_reg_505, "x_assign_reg_505");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, p_Result_s_reg_510, "p_Result_s_reg_510");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, p_Val2_5_fu_400_p3, "p_Val2_5_fu_400_p3");
    sc_trace(mVcdFile, p_Val2_5_reg_515, "p_Val2_5_reg_515");
    sc_trace(mVcdFile, best_class_1_reg_98, "best_class_1_reg_98");
    sc_trace(mVcdFile, best_class_reg_109, "best_class_reg_109");
    sc_trace(mVcdFile, global_min_dist_reg_121, "global_min_dist_reg_121");
    sc_trace(mVcdFile, phi_mul_reg_133, "phi_mul_reg_133");
    sc_trace(mVcdFile, class_min_dist_reg_145, "class_min_dist_reg_145");
    sc_trace(mVcdFile, p_reg_157, "p_reg_157");
    sc_trace(mVcdFile, tmp_10_cast_fu_232_p1, "tmp_10_cast_fu_232_p1");
    sc_trace(mVcdFile, tmp_1_fu_217_p1, "tmp_1_fu_217_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, grp_fu_173_p0, "grp_fu_173_p0");
    sc_trace(mVcdFile, tmp_1_cast_fu_222_p1, "tmp_1_cast_fu_222_p1");
    sc_trace(mVcdFile, tmp_2_fu_226_p2, "tmp_2_fu_226_p2");
    sc_trace(mVcdFile, class_min_dist_cast_fu_237_p1, "class_min_dist_cast_fu_237_p1");
    sc_trace(mVcdFile, tmp_3_fu_241_p2, "tmp_3_fu_241_p2");
    sc_trace(mVcdFile, tmp_4_cast_fu_262_p1, "tmp_4_cast_fu_262_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_266_p1, "tmp_5_cast_fu_266_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_279_p1, "p_Val2_s_fu_279_p1");
    sc_trace(mVcdFile, tmp_V_1_fu_300_p1, "tmp_V_1_fu_300_p1");
    sc_trace(mVcdFile, mantissa_V_fu_304_p4, "mantissa_V_fu_304_p4");
    sc_trace(mVcdFile, tmp_V_fu_290_p4, "tmp_V_fu_290_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i_cast1_fu_318_p1, "tmp_i_i_i_i_cast1_fu_318_p1");
    sc_trace(mVcdFile, sh_assign_fu_322_p2, "sh_assign_fu_322_p2");
    sc_trace(mVcdFile, tmp_i_i_i_fu_336_p2, "tmp_i_i_i_fu_336_p2");
    sc_trace(mVcdFile, isNeg_fu_328_p3, "isNeg_fu_328_p3");
    sc_trace(mVcdFile, tmp_i_i_i_cast_fu_342_p1, "tmp_i_i_i_cast_fu_342_p1");
    sc_trace(mVcdFile, ush_fu_346_p3, "ush_fu_346_p3");
    sc_trace(mVcdFile, sh_assign_2_cast_fu_354_p1, "sh_assign_2_cast_fu_354_p1");
    sc_trace(mVcdFile, tmp_1_i_i_i_cast_fu_362_p1, "tmp_1_i_i_i_cast_fu_362_p1");
    sc_trace(mVcdFile, mantissa_V_1_cast_fu_314_p1, "mantissa_V_1_cast_fu_314_p1");
    sc_trace(mVcdFile, tmp_1_i_i_i_fu_358_p1, "tmp_1_i_i_i_fu_358_p1");
    sc_trace(mVcdFile, r_V_fu_366_p2, "r_V_fu_366_p2");
    sc_trace(mVcdFile, tmp_9_fu_378_p3, "tmp_9_fu_378_p3");
    sc_trace(mVcdFile, r_V_1_fu_372_p2, "r_V_1_fu_372_p2");
    sc_trace(mVcdFile, tmp_5_fu_386_p1, "tmp_5_fu_386_p1");
    sc_trace(mVcdFile, tmp_7_fu_390_p4, "tmp_7_fu_390_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, result_V_1_fu_408_p2, "result_V_1_fu_408_p2");
    sc_trace(mVcdFile, p_Val2_6_fu_413_p3, "p_Val2_6_fu_413_p3");
    sc_trace(mVcdFile, grp_fu_431_p0, "grp_fu_431_p0");
    sc_trace(mVcdFile, diff_cast_fu_276_p1, "diff_cast_fu_276_p1");
    sc_trace(mVcdFile, grp_fu_431_p1, "grp_fu_431_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

classify_image::~classify_image() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete centroids_0_U;
    delete kmeans_top_ddiv_64ns_64ns_64_31_1_U1;
    delete kmeans_top_uitodp_32ns_64_6_1_U2;
    delete kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3;
}

void classify_image::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void classify_image::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv64_412E848000000000;
}

void classify_image::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_205_p2.read()))) {
        best_class_1_reg_98 = c_reg_452.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        best_class_1_reg_98 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_205_p2.read()))) {
        best_class_reg_109 = c_0_best_class_fu_247_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        best_class_reg_109 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_186_p2.read(), ap_const_lv1_0))) {
        class_min_dist_reg_145 = ap_const_lv27_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        class_min_dist_reg_145 = grp_fu_431_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_205_p2.read()))) {
        global_min_dist_reg_121 = class_min_dist_0_glo_fu_254_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        global_min_dist_reg_121 = ap_const_lv32_FFFFFFFF;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_186_p2.read(), ap_const_lv1_0))) {
        p_reg_157 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_reg_157 = p_1_reg_465.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_205_p2.read()))) {
        phi_mul_reg_133 = next_mul_reg_439.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_mul_reg_133 = ap_const_lv13_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        best_class_1_cast3_reg_444 = best_class_1_cast3_fu_182_p1.read();
        c_reg_452 = c_fu_192_p2.read();
        next_mul_reg_439 = next_mul_fu_176_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        diff_reg_490 = diff_fu_270_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_1_reg_465 = p_1_fu_211_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        p_Result_s_reg_510 = p_Val2_s_fu_279_p1.read().range(63, 63);
        p_Val2_5_reg_515 = p_Val2_5_fu_400_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_s_reg_500 = grp_fu_173_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        x_assign_reg_505 = grp_fu_168_p2.read();
    }
}

void classify_image::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void classify_image::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void classify_image::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void classify_image::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void classify_image::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void classify_image::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void classify_image::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void classify_image::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void classify_image::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void classify_image::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void classify_image::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void classify_image::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void classify_image::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void classify_image::thread_ap_return_0() {
    ap_return_0 = best_class_reg_109.read();
}

void classify_image::thread_ap_return_1() {
    ap_return_1 = p_Val2_6_fu_413_p3.read();
}

void classify_image::thread_best_class_1_cast3_fu_182_p1() {
    best_class_1_cast3_fu_182_p1 = esl_zext<32,4>(best_class_1_reg_98.read());
}

void classify_image::thread_c_0_best_class_fu_247_p3() {
    c_0_best_class_fu_247_p3 = (!tmp_3_fu_241_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_241_p2.read()[0].to_bool())? best_class_1_cast3_reg_444.read(): best_class_reg_109.read());
}

void classify_image::thread_c_fu_192_p2() {
    c_fu_192_p2 = (!best_class_1_reg_98.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(best_class_1_reg_98.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void classify_image::thread_centroids_0_address0() {
    centroids_0_address0 =  (sc_lv<13>) (tmp_10_cast_fu_232_p1.read());
}

void classify_image::thread_centroids_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        centroids_0_ce0 = ap_const_logic_1;
    } else {
        centroids_0_ce0 = ap_const_logic_0;
    }
}

void classify_image::thread_class_min_dist_0_glo_fu_254_p3() {
    class_min_dist_0_glo_fu_254_p3 = (!tmp_3_fu_241_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_241_p2.read()[0].to_bool())? class_min_dist_cast_fu_237_p1.read(): global_min_dist_reg_121.read());
}

void classify_image::thread_class_min_dist_cast_fu_237_p1() {
    class_min_dist_cast_fu_237_p1 = esl_sext<32,27>(class_min_dist_reg_145.read());
}

void classify_image::thread_diff_cast_fu_276_p1() {
    diff_cast_fu_276_p1 = esl_sext<18,9>(diff_reg_490.read());
}

void classify_image::thread_diff_fu_270_p2() {
    diff_fu_270_p2 = (!tmp_4_cast_fu_262_p1.read().is_01() || !tmp_5_cast_fu_266_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_4_cast_fu_262_p1.read()) - sc_biguint<9>(tmp_5_cast_fu_266_p1.read()));
}

void classify_image::thread_exitcond2_fu_186_p2() {
    exitcond2_fu_186_p2 = (!best_class_1_reg_98.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(best_class_1_reg_98.read() == ap_const_lv4_A);
}

void classify_image::thread_exitcond_fu_205_p2() {
    exitcond_fu_205_p2 = (!p_reg_157.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(p_reg_157.read() == ap_const_lv10_310);
}

void classify_image::thread_grp_fu_173_p0() {
    grp_fu_173_p0 = (!ap_const_lv32_1.is_01() || !global_min_dist_reg_121.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(global_min_dist_reg_121.read()));
}

void classify_image::thread_grp_fu_431_p0() {
    grp_fu_431_p0 =  (sc_lv<9>) (diff_cast_fu_276_p1.read());
}

void classify_image::thread_grp_fu_431_p1() {
    grp_fu_431_p1 =  (sc_lv<9>) (diff_cast_fu_276_p1.read());
}

void classify_image::thread_image_r_address0() {
    image_r_address0 =  (sc_lv<10>) (tmp_1_fu_217_p1.read());
}

void classify_image::thread_image_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        image_r_ce0 = ap_const_logic_1;
    } else {
        image_r_ce0 = ap_const_logic_0;
    }
}

void classify_image::thread_isNeg_fu_328_p3() {
    isNeg_fu_328_p3 = sh_assign_fu_322_p2.read().range(11, 11);
}

void classify_image::thread_mantissa_V_1_cast_fu_314_p1() {
    mantissa_V_1_cast_fu_314_p1 = esl_zext<137,54>(mantissa_V_fu_304_p4.read());
}

void classify_image::thread_mantissa_V_fu_304_p4() {
    mantissa_V_fu_304_p4 = esl_concat<53,1>(esl_concat<1,52>(ap_const_lv1_1, tmp_V_1_fu_300_p1.read()), ap_const_lv1_0);
}

void classify_image::thread_next_mul_fu_176_p2() {
    next_mul_fu_176_p2 = (!phi_mul_reg_133.read().is_01() || !ap_const_lv13_310.is_01())? sc_lv<13>(): (sc_biguint<13>(phi_mul_reg_133.read()) + sc_biguint<13>(ap_const_lv13_310));
}

void classify_image::thread_p_1_fu_211_p2() {
    p_1_fu_211_p2 = (!p_reg_157.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(p_reg_157.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void classify_image::thread_p_Val2_5_fu_400_p3() {
    p_Val2_5_fu_400_p3 = (!isNeg_fu_328_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_328_p3.read()[0].to_bool())? tmp_5_fu_386_p1.read(): tmp_7_fu_390_p4.read());
}

void classify_image::thread_p_Val2_6_fu_413_p3() {
    p_Val2_6_fu_413_p3 = (!p_Result_s_reg_510.read()[0].is_01())? sc_lv<32>(): ((p_Result_s_reg_510.read()[0].to_bool())? result_V_1_fu_408_p2.read(): p_Val2_5_reg_515.read());
}

void classify_image::thread_p_Val2_s_fu_279_p1() {
    p_Val2_s_fu_279_p1 = x_assign_reg_505.read();
}

void classify_image::thread_r_V_1_fu_372_p2() {
    r_V_1_fu_372_p2 = (!tmp_1_i_i_i_fu_358_p1.read().is_01())? sc_lv<137>(): mantissa_V_1_cast_fu_314_p1.read() << (unsigned short)tmp_1_i_i_i_fu_358_p1.read().to_uint();
}

void classify_image::thread_r_V_fu_366_p2() {
    r_V_fu_366_p2 = (!tmp_1_i_i_i_cast_fu_362_p1.read().is_01())? sc_lv<54>(): mantissa_V_fu_304_p4.read() >> (unsigned short)tmp_1_i_i_i_cast_fu_362_p1.read().to_uint();
}

void classify_image::thread_result_V_1_fu_408_p2() {
    result_V_1_fu_408_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_5_reg_515.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_5_reg_515.read()));
}

void classify_image::thread_sh_assign_2_cast_fu_354_p1() {
    sh_assign_2_cast_fu_354_p1 = esl_sext<32,12>(ush_fu_346_p3.read());
}

void classify_image::thread_sh_assign_fu_322_p2() {
    sh_assign_fu_322_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_i_cast1_fu_318_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_i_cast1_fu_318_p1.read()));
}

void classify_image::thread_tmp_10_cast_fu_232_p1() {
    tmp_10_cast_fu_232_p1 = esl_zext<64,13>(tmp_2_fu_226_p2.read());
}

void classify_image::thread_tmp_1_cast_fu_222_p1() {
    tmp_1_cast_fu_222_p1 = esl_zext<13,10>(p_reg_157.read());
}

void classify_image::thread_tmp_1_fu_217_p1() {
    tmp_1_fu_217_p1 = esl_zext<64,10>(p_reg_157.read());
}

void classify_image::thread_tmp_1_i_i_i_cast_fu_362_p1() {
    tmp_1_i_i_i_cast_fu_362_p1 = esl_zext<54,32>(sh_assign_2_cast_fu_354_p1.read());
}

void classify_image::thread_tmp_1_i_i_i_fu_358_p1() {
    tmp_1_i_i_i_fu_358_p1 = esl_zext<137,32>(sh_assign_2_cast_fu_354_p1.read());
}

void classify_image::thread_tmp_2_fu_226_p2() {
    tmp_2_fu_226_p2 = (!phi_mul_reg_133.read().is_01() || !tmp_1_cast_fu_222_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(phi_mul_reg_133.read()) + sc_biguint<13>(tmp_1_cast_fu_222_p1.read()));
}

void classify_image::thread_tmp_3_fu_241_p2() {
    tmp_3_fu_241_p2 = (!class_min_dist_cast_fu_237_p1.read().is_01() || !global_min_dist_reg_121.read().is_01())? sc_lv<1>(): (sc_biguint<32>(class_min_dist_cast_fu_237_p1.read()) < sc_biguint<32>(global_min_dist_reg_121.read()));
}

void classify_image::thread_tmp_4_cast_fu_262_p1() {
    tmp_4_cast_fu_262_p1 = esl_zext<9,8>(image_r_q0.read());
}

void classify_image::thread_tmp_5_cast_fu_266_p1() {
    tmp_5_cast_fu_266_p1 = esl_zext<9,8>(centroids_0_q0.read());
}

void classify_image::thread_tmp_5_fu_386_p1() {
    tmp_5_fu_386_p1 = esl_zext<32,1>(tmp_9_fu_378_p3.read());
}

void classify_image::thread_tmp_7_fu_390_p4() {
    tmp_7_fu_390_p4 = r_V_1_fu_372_p2.read().range(84, 53);
}

void classify_image::thread_tmp_9_fu_378_p3() {
    tmp_9_fu_378_p3 = r_V_fu_366_p2.read().range(53, 53);
}

void classify_image::thread_tmp_V_1_fu_300_p1() {
    tmp_V_1_fu_300_p1 = p_Val2_s_fu_279_p1.read().range(52-1, 0);
}

void classify_image::thread_tmp_V_fu_290_p4() {
    tmp_V_fu_290_p4 = p_Val2_s_fu_279_p1.read().range(62, 52);
}

void classify_image::thread_tmp_i_i_i_cast_fu_342_p1() {
    tmp_i_i_i_cast_fu_342_p1 = esl_sext<12,11>(tmp_i_i_i_fu_336_p2.read());
}

void classify_image::thread_tmp_i_i_i_fu_336_p2() {
    tmp_i_i_i_fu_336_p2 = (!ap_const_lv11_3FF.is_01() || !tmp_V_fu_290_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(tmp_V_fu_290_p4.read()));
}

void classify_image::thread_tmp_i_i_i_i_cast1_fu_318_p1() {
    tmp_i_i_i_i_cast1_fu_318_p1 = esl_zext<12,11>(tmp_V_fu_290_p4.read());
}

void classify_image::thread_ush_fu_346_p3() {
    ush_fu_346_p3 = (!isNeg_fu_328_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_fu_328_p3.read()[0].to_bool())? tmp_i_i_i_cast_fu_342_p1.read(): sh_assign_fu_322_p2.read());
}

void classify_image::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond2_fu_186_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_205_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

}

