// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _classify_image_HH_
#define _classify_image_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "kmeans_top_ddiv_64ns_64ns_64_31_1.h"
#include "kmeans_top_uitodp_32ns_64_6_1.h"
#include "kmeans_top_mac_muladd_9s_9s_27s_27_1_1.h"
#include "classify_image_centroids_0.h"

namespace ap_rtl {

struct classify_image : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > image_r_address0;
    sc_out< sc_logic > image_r_ce0;
    sc_in< sc_lv<8> > image_r_q0;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<64> > ap_var_for_const0;


    // Module declarations
    classify_image(sc_module_name name);
    SC_HAS_PROCESS(classify_image);

    ~classify_image();

    sc_trace_file* mVcdFile;

    classify_image_centroids_0* centroids_0_U;
    kmeans_top_ddiv_64ns_64ns_64_31_1<1,31,64,64,64>* kmeans_top_ddiv_64ns_64ns_64_31_1_U1;
    kmeans_top_uitodp_32ns_64_6_1<1,6,32,64>* kmeans_top_uitodp_32ns_64_6_1_U2;
    kmeans_top_mac_muladd_9s_9s_27s_27_1_1<1,1,9,9,27,27>* kmeans_top_mac_muladd_9s_9s_27s_27_1_1_U3;
    sc_signal< sc_lv<43> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<13> > centroids_0_address0;
    sc_signal< sc_logic > centroids_0_ce0;
    sc_signal< sc_lv<8> > centroids_0_q0;
    sc_signal< sc_lv<13> > next_mul_fu_176_p2;
    sc_signal< sc_lv<13> > next_mul_reg_439;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > best_class_1_cast3_fu_182_p1;
    sc_signal< sc_lv<32> > best_class_1_cast3_reg_444;
    sc_signal< sc_lv<4> > c_fu_192_p2;
    sc_signal< sc_lv<4> > c_reg_452;
    sc_signal< sc_lv<1> > exitcond2_fu_186_p2;
    sc_signal< sc_lv<10> > p_1_fu_211_p2;
    sc_signal< sc_lv<10> > p_1_reg_465;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond_fu_205_p2;
    sc_signal< sc_lv<32> > c_0_best_class_fu_247_p3;
    sc_signal< sc_lv<32> > class_min_dist_0_glo_fu_254_p3;
    sc_signal< sc_lv<9> > diff_fu_270_p2;
    sc_signal< sc_lv<9> > diff_reg_490;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<27> > grp_fu_431_p3;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > grp_fu_173_p1;
    sc_signal< sc_lv<64> > tmp_s_reg_500;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<64> > grp_fu_168_p2;
    sc_signal< sc_lv<64> > x_assign_reg_505;
    sc_signal< sc_logic > ap_CS_fsm_state41;
    sc_signal< sc_lv<1> > p_Result_s_reg_510;
    sc_signal< sc_logic > ap_CS_fsm_state42;
    sc_signal< sc_lv<32> > p_Val2_5_fu_400_p3;
    sc_signal< sc_lv<32> > p_Val2_5_reg_515;
    sc_signal< sc_lv<4> > best_class_1_reg_98;
    sc_signal< sc_lv<32> > best_class_reg_109;
    sc_signal< sc_lv<32> > global_min_dist_reg_121;
    sc_signal< sc_lv<13> > phi_mul_reg_133;
    sc_signal< sc_lv<27> > class_min_dist_reg_145;
    sc_signal< sc_lv<10> > p_reg_157;
    sc_signal< sc_lv<64> > tmp_10_cast_fu_232_p1;
    sc_signal< sc_lv<64> > tmp_1_fu_217_p1;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<32> > grp_fu_173_p0;
    sc_signal< sc_lv<13> > tmp_1_cast_fu_222_p1;
    sc_signal< sc_lv<13> > tmp_2_fu_226_p2;
    sc_signal< sc_lv<32> > class_min_dist_cast_fu_237_p1;
    sc_signal< sc_lv<1> > tmp_3_fu_241_p2;
    sc_signal< sc_lv<9> > tmp_4_cast_fu_262_p1;
    sc_signal< sc_lv<9> > tmp_5_cast_fu_266_p1;
    sc_signal< sc_lv<64> > p_Val2_s_fu_279_p1;
    sc_signal< sc_lv<52> > tmp_V_1_fu_300_p1;
    sc_signal< sc_lv<54> > mantissa_V_fu_304_p4;
    sc_signal< sc_lv<11> > tmp_V_fu_290_p4;
    sc_signal< sc_lv<12> > tmp_i_i_i_i_cast1_fu_318_p1;
    sc_signal< sc_lv<12> > sh_assign_fu_322_p2;
    sc_signal< sc_lv<11> > tmp_i_i_i_fu_336_p2;
    sc_signal< sc_lv<1> > isNeg_fu_328_p3;
    sc_signal< sc_lv<12> > tmp_i_i_i_cast_fu_342_p1;
    sc_signal< sc_lv<12> > ush_fu_346_p3;
    sc_signal< sc_lv<32> > sh_assign_2_cast_fu_354_p1;
    sc_signal< sc_lv<54> > tmp_1_i_i_i_cast_fu_362_p1;
    sc_signal< sc_lv<137> > mantissa_V_1_cast_fu_314_p1;
    sc_signal< sc_lv<137> > tmp_1_i_i_i_fu_358_p1;
    sc_signal< sc_lv<54> > r_V_fu_366_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_378_p3;
    sc_signal< sc_lv<137> > r_V_1_fu_372_p2;
    sc_signal< sc_lv<32> > tmp_5_fu_386_p1;
    sc_signal< sc_lv<32> > tmp_7_fu_390_p4;
    sc_signal< sc_logic > ap_CS_fsm_state43;
    sc_signal< sc_lv<32> > result_V_1_fu_408_p2;
    sc_signal< sc_lv<32> > p_Val2_6_fu_413_p3;
    sc_signal< sc_lv<9> > grp_fu_431_p0;
    sc_signal< sc_lv<18> > diff_cast_fu_276_p1;
    sc_signal< sc_lv<9> > grp_fu_431_p1;
    sc_signal< sc_lv<43> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<43> ap_ST_fsm_state1;
    static const sc_lv<43> ap_ST_fsm_state2;
    static const sc_lv<43> ap_ST_fsm_state3;
    static const sc_lv<43> ap_ST_fsm_state4;
    static const sc_lv<43> ap_ST_fsm_state5;
    static const sc_lv<43> ap_ST_fsm_state6;
    static const sc_lv<43> ap_ST_fsm_state7;
    static const sc_lv<43> ap_ST_fsm_state8;
    static const sc_lv<43> ap_ST_fsm_state9;
    static const sc_lv<43> ap_ST_fsm_state10;
    static const sc_lv<43> ap_ST_fsm_state11;
    static const sc_lv<43> ap_ST_fsm_state12;
    static const sc_lv<43> ap_ST_fsm_state13;
    static const sc_lv<43> ap_ST_fsm_state14;
    static const sc_lv<43> ap_ST_fsm_state15;
    static const sc_lv<43> ap_ST_fsm_state16;
    static const sc_lv<43> ap_ST_fsm_state17;
    static const sc_lv<43> ap_ST_fsm_state18;
    static const sc_lv<43> ap_ST_fsm_state19;
    static const sc_lv<43> ap_ST_fsm_state20;
    static const sc_lv<43> ap_ST_fsm_state21;
    static const sc_lv<43> ap_ST_fsm_state22;
    static const sc_lv<43> ap_ST_fsm_state23;
    static const sc_lv<43> ap_ST_fsm_state24;
    static const sc_lv<43> ap_ST_fsm_state25;
    static const sc_lv<43> ap_ST_fsm_state26;
    static const sc_lv<43> ap_ST_fsm_state27;
    static const sc_lv<43> ap_ST_fsm_state28;
    static const sc_lv<43> ap_ST_fsm_state29;
    static const sc_lv<43> ap_ST_fsm_state30;
    static const sc_lv<43> ap_ST_fsm_state31;
    static const sc_lv<43> ap_ST_fsm_state32;
    static const sc_lv<43> ap_ST_fsm_state33;
    static const sc_lv<43> ap_ST_fsm_state34;
    static const sc_lv<43> ap_ST_fsm_state35;
    static const sc_lv<43> ap_ST_fsm_state36;
    static const sc_lv<43> ap_ST_fsm_state37;
    static const sc_lv<43> ap_ST_fsm_state38;
    static const sc_lv<43> ap_ST_fsm_state39;
    static const sc_lv<43> ap_ST_fsm_state40;
    static const sc_lv<43> ap_ST_fsm_state41;
    static const sc_lv<43> ap_ST_fsm_state42;
    static const sc_lv<43> ap_ST_fsm_state43;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<32> ap_const_lv32_29;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<27> ap_const_lv27_0;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<64> ap_const_lv64_412E848000000000;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<13> ap_const_lv13_310;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<10> ap_const_lv10_310;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<32> ap_const_lv32_35;
    static const sc_lv<32> ap_const_lv32_54;
    static const sc_lv<32> ap_const_lv32_2A;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state41();
    void thread_ap_CS_fsm_state42();
    void thread_ap_CS_fsm_state43();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_best_class_1_cast3_fu_182_p1();
    void thread_c_0_best_class_fu_247_p3();
    void thread_c_fu_192_p2();
    void thread_centroids_0_address0();
    void thread_centroids_0_ce0();
    void thread_class_min_dist_0_glo_fu_254_p3();
    void thread_class_min_dist_cast_fu_237_p1();
    void thread_diff_cast_fu_276_p1();
    void thread_diff_fu_270_p2();
    void thread_exitcond2_fu_186_p2();
    void thread_exitcond_fu_205_p2();
    void thread_grp_fu_173_p0();
    void thread_grp_fu_431_p0();
    void thread_grp_fu_431_p1();
    void thread_image_r_address0();
    void thread_image_r_ce0();
    void thread_isNeg_fu_328_p3();
    void thread_mantissa_V_1_cast_fu_314_p1();
    void thread_mantissa_V_fu_304_p4();
    void thread_next_mul_fu_176_p2();
    void thread_p_1_fu_211_p2();
    void thread_p_Val2_5_fu_400_p3();
    void thread_p_Val2_6_fu_413_p3();
    void thread_p_Val2_s_fu_279_p1();
    void thread_r_V_1_fu_372_p2();
    void thread_r_V_fu_366_p2();
    void thread_result_V_1_fu_408_p2();
    void thread_sh_assign_2_cast_fu_354_p1();
    void thread_sh_assign_fu_322_p2();
    void thread_tmp_10_cast_fu_232_p1();
    void thread_tmp_1_cast_fu_222_p1();
    void thread_tmp_1_fu_217_p1();
    void thread_tmp_1_i_i_i_cast_fu_362_p1();
    void thread_tmp_1_i_i_i_fu_358_p1();
    void thread_tmp_2_fu_226_p2();
    void thread_tmp_3_fu_241_p2();
    void thread_tmp_4_cast_fu_262_p1();
    void thread_tmp_5_cast_fu_266_p1();
    void thread_tmp_5_fu_386_p1();
    void thread_tmp_7_fu_390_p4();
    void thread_tmp_9_fu_378_p3();
    void thread_tmp_V_1_fu_300_p1();
    void thread_tmp_V_fu_290_p4();
    void thread_tmp_i_i_i_cast_fu_342_p1();
    void thread_tmp_i_i_i_fu_336_p2();
    void thread_tmp_i_i_i_i_cast1_fu_318_p1();
    void thread_ush_fu_346_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
