// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kmeans_top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200tsbg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.430250,HLS_SYN_LAT=448,HLS_SYN_TPT=none,HLS_SYN_MEM=1568,HLS_SYN_DSP=512,HLS_SYN_FF=31922,HLS_SYN_LUT=59662,HLS_VERSION=2018_3}" *)

module kmeans_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        image_r_address0,
        image_r_ce0,
        image_r_q0,
        image_r_address1,
        image_r_ce1,
        image_r_q1,
        result_address0,
        result_ce0,
        result_we0,
        result_d0,
        result_address1,
        result_ce1,
        result_we1,
        result_d1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] image_r_address0;
output   image_r_ce0;
input  [7:0] image_r_q0;
output  [9:0] image_r_address1;
output   image_r_ce1;
input  [7:0] image_r_q1;
output  [0:0] result_address0;
output   result_ce0;
output   result_we0;
output  [31:0] result_d0;
output  [0:0] result_address1;
output   result_ce1;
output   result_we1;
output  [31:0] result_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg result_ce0;
reg result_we0;
reg result_ce1;
reg result_we1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_classify_image_fu_45_ap_start;
wire    grp_classify_image_fu_45_ap_done;
wire    grp_classify_image_fu_45_ap_idle;
wire    grp_classify_image_fu_45_ap_ready;
wire   [9:0] grp_classify_image_fu_45_image_r_address0;
wire    grp_classify_image_fu_45_image_r_ce0;
wire   [9:0] grp_classify_image_fu_45_image_r_address1;
wire    grp_classify_image_fu_45_image_r_ce1;
wire   [31:0] grp_classify_image_fu_45_ap_return_0;
wire   [31:0] grp_classify_image_fu_45_ap_return_1;
reg    grp_classify_image_fu_45_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_classify_image_fu_45_ap_start_reg = 1'b0;
end

classify_image grp_classify_image_fu_45(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_classify_image_fu_45_ap_start),
    .ap_done(grp_classify_image_fu_45_ap_done),
    .ap_idle(grp_classify_image_fu_45_ap_idle),
    .ap_ready(grp_classify_image_fu_45_ap_ready),
    .image_r_address0(grp_classify_image_fu_45_image_r_address0),
    .image_r_ce0(grp_classify_image_fu_45_image_r_ce0),
    .image_r_q0(image_r_q0),
    .image_r_address1(grp_classify_image_fu_45_image_r_address1),
    .image_r_ce1(grp_classify_image_fu_45_image_r_ce1),
    .image_r_q1(image_r_q1),
    .ap_return_0(grp_classify_image_fu_45_ap_return_0),
    .ap_return_1(grp_classify_image_fu_45_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_classify_image_fu_45_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_classify_image_fu_45_ap_start_reg <= 1'b1;
        end else if ((grp_classify_image_fu_45_ap_ready == 1'b1)) begin
            grp_classify_image_fu_45_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((grp_classify_image_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_classify_image_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_classify_image_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        result_ce0 = 1'b1;
    end else begin
        result_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_classify_image_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        result_ce1 = 1'b1;
    end else begin
        result_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_classify_image_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        result_we0 = 1'b1;
    end else begin
        result_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_classify_image_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        result_we1 = 1'b1;
    end else begin
        result_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_classify_image_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_classify_image_fu_45_ap_start = grp_classify_image_fu_45_ap_start_reg;

assign image_r_address0 = grp_classify_image_fu_45_image_r_address0;

assign image_r_address1 = grp_classify_image_fu_45_image_r_address1;

assign image_r_ce0 = grp_classify_image_fu_45_image_r_ce0;

assign image_r_ce1 = grp_classify_image_fu_45_image_r_ce1;

assign result_address0 = 64'd0;

assign result_address1 = 64'd1;

assign result_d0 = grp_classify_image_fu_45_ap_return_0;

assign result_d1 = grp_classify_image_fu_45_ap_return_1;

endmodule //kmeans_top
